version: "3.8"

services:
  springboot:
    build: .
    container_name: ems-app
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      DB_URL: ${DB_URL}
      DB_NAME: ${DB_NAME}
      MAIL_URL: ${MAIL_URL}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
    ports:
      - "8082:8080"

