version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ems
    environment:
      - DB_URL=${DB_URL}
      - DB_NAME=${DB_NAME}
      - MAIL_URL=${MAIL_URL}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - PROFILES_ACTIVE=${PROFILES_ACTIVE}
        FRONTEND_DOMAIN=${FRONTEND_DOMAIN}
        SECRET_KEY=${SECRET_KEY}
    ports:
      - "8082:8080"
